server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
  datasource:
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop_base?useUnicode=true
#
#security:
#  jwt:
#    secret-key: Tranvanphuc123456789Tranvanphuc123456789Tranvanphuc123456789Tranvanphuc123456789
#    refresh-token:
#      expiration: '120000'
#    expiration: '60000'